# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_not_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(704, 305)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.about_link_button = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.about_link_button.setGeometry(QtCore.QRect(570, 180, 121, 41))
        self.about_link_button.setObjectName("about_link_button")
        self.check_update_link_button = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.check_update_link_button.setGeometry(QtCore.QRect(460, 220, 231, 41))
        self.check_update_link_button.setObjectName("check_update_link_button")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(140, 10, 411, 130))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("汉仪文黑-85W")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(45)
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")
        self.horizontalLayout.addWidget(self.login_button)
        self.reg_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(45)
        self.reg_button.setFont(font)
        self.reg_button.setObjectName("reg_button")
        self.horizontalLayout.addWidget(self.reg_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 704, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.about_link_button.setText(_translate("MainWindow", "About/关于"))
        self.check_update_link_button.setText(_translate("MainWindow", "CheckForUpdate/检查更新"))
        self.label.setText(_translate("MainWindow", "图书馆查阅系统Ver1.0"))
        self.label_2.setText(_translate("MainWindow", "您看起来尚未登录"))
        self.login_button.setText(_translate("MainWindow", "登录"))
        self.reg_button.setText(_translate("MainWindow", "注册"))
