# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 50, 41, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(120, 90, 31, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(100, 120, 54, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(120, 150, 31, 16))
        self.label_5.setObjectName("label_5")
        self.user_not_robot_input = QtWidgets.QLineEdit(Dialog)
        self.user_not_robot_input.setGeometry(QtCore.QRect(160, 180, 113, 20))
        self.user_not_robot_input.setObjectName("user_not_robot_input")
        self.user_name_input = QtWidgets.QLineEdit(Dialog)
        self.user_name_input.setGeometry(QtCore.QRect(160, 50, 113, 20))
        self.user_name_input.setText("")
        self.user_name_input.setObjectName("user_name_input")
        self.user_password_input = QtWidgets.QLineEdit(Dialog)
        self.user_password_input.setGeometry(QtCore.QRect(160, 90, 113, 20))
        self.user_password_input.setText("")
        self.user_password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.user_password_input.setObjectName("user_password_input")
        self.user_psw_agent_input = QtWidgets.QLineEdit(Dialog)
        self.user_psw_agent_input.setGeometry(QtCore.QRect(160, 120, 113, 20))
        self.user_psw_agent_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.user_psw_agent_input.setObjectName("user_psw_agent_input")
        self.user_email_input = QtWidgets.QLineEdit(Dialog)
        self.user_email_input.setGeometry(QtCore.QRect(160, 150, 113, 20))
        self.user_email_input.setObjectName("user_email_input")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(300, 40, 77, 54))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.yes_pushButton = QtWidgets.QPushButton(self.widget)
        self.yes_pushButton.setObjectName("yes_pushButton")
        self.verticalLayout.addWidget(self.yes_pushButton)
        self.no_pushButton = QtWidgets.QPushButton(self.widget)
        self.no_pushButton.setObjectName("no_pushButton")
        self.verticalLayout.addWidget(self.no_pushButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "*用户名"))
        self.label_2.setText(_translate("Dialog", "*密码"))
        self.label_3.setText(_translate("Dialog", "*请在右边输入：我是真人"))
        self.label_4.setText(_translate("Dialog", "*重复密码"))
        self.label_5.setText(_translate("Dialog", "邮箱"))
        self.user_not_robot_input.setPlaceholderText(_translate("Dialog", "我是机器人"))
        self.user_name_input.setPlaceholderText(_translate("Dialog", "123456"))
        self.user_password_input.setPlaceholderText(_translate("Dialog", "sbc@.bAgE"))
        self.user_psw_agent_input.setPlaceholderText(_translate("Dialog", "sbc@.bAgE"))
        self.user_email_input.setPlaceholderText(_translate("Dialog", "qwert@000.moc"))
        self.yes_pushButton.setText(_translate("Dialog", "确定"))
        self.no_pushButton.setText(_translate("Dialog", "取消"))
